### ISSUE TITLE
singleplayer is jokes and multiplayer probably doesn't work, just fix those lol

### ISSUE THREAD

**Issue by izabeleb** [izabeleb/MinesweeperMulti#25]

**Comment by Kuronym** [comment]
Dear Izabeleb/Minesweepermulti,

I am ecstatic to be working on your team. We will do great things.

Please forward my respects to the rest of the team members.

Sincerely,
Kuronym

**Comment by joshmeranda** [comment]
@Kuronym any updates on this?!?!?! Please we're relying on you
